### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by MaheshCapcee** [ejeinc/RajawaliCardboardExample#9]
Hii...
 i am Mahesh  
downloaded this project and imported my android studio and i am run to my device is error

07-25 13:01:21.188 17425-18146/com.eje_c.rajawalicardboard E/dalvikvm-heap: Out of memory on a 102760464-byte allocation.
07-25 13:01:21.218 17425-18146/com.eje_c.rajawalicardboard E/AndroidRuntime: FATAL EXCEPTION: GLThread 5832
                                                                             Process: com.eje_c.rajawalicardboard, PID: 17425
                                                                             java.lang.OutOfMemoryError
                                                                                 at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                                                 at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:594)
                                                                                 at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:429)
                                                                                 at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:452)
                                                                                 at org.rajawali3d.materials.textures.ASingleTexture.setResourceId(ASingleTexture.java:92)
                                                                                 at org.rajawali3d.materials.textures.Texture.<init>(Texture.java:32)
                                                                                 at com.eje_c.rajawalicardboard.MyRenderer.initScene(MyRenderer.java:21)
                                                                                 at org.rajawali3d.renderer.RajawaliRenderer.onRenderSurfaceSizeChanged(RajawaliRenderer.java:348)
                                                                                 at org.rajawali3d.cardboard.RajawaliCardboardRenderer.onSurfaceChanged(RajawaliCardboardRenderer.java:65)
                                                                                 at com.google.vrtoolkit.cardboard.CardboardView$StereoRendererHelper.onSurfaceChanged(CardboardView.java:1362)
                                                                                 at com.google.vrtoolkit.cardboard.CardboardView$RendererHelper.onSurfaceChanged(CardboardView.java:1143)
                                                                                 at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1514)
                                                                                 at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1242)

please helpp

**Comment by MaheshCapcee** [comment]
i am closed that issue now show a black screen on screen please help...
